const enContent = {
    COURSES: [
        {
            id: 'c0', icon: '📊', title: 'Trading Basics', desc: 'The process of buying and selling assets, liquidity, imbalance, and basic concepts.',
            text: `📊 What is Trading\n\nTrading is the process of buying and selling financial assets to earn from price changes.\nA trader analyzes the market, charts, and news to determine where the price might go.\n\n💧 Liquidity\nLiquidity is the amount of money and orders in the market.\nThe more liquidity there is, the easier it is to buy or sell an asset.\n\n⚡ Imbalance\nAn area on the chart where the price moved very fast and didn't leave any trades.\nSuch areas often pull the price back later.\n\n📉 Support\nA price level where buyers actively start buying the asset.\n\n📈 Resistance\nA price level where sellers actively start selling.\n\n🕯 Candlestick Chart\nCandlesticks show the price movement: open, close, high, low.\nA green candle means the price went up. Red means it went down.\n\n🎯 Trend\nThe general direction of the price: uptrend, downtrend, sideways.\n\n📊 Volatility\nThe speed and strength of price changes. Higher volatility means a faster market.\n\n🧠 Market Manipulation\nArtificial price movement to grab stop-orders.\n\n🪤 Liquidity Grab\nA specific level breakout right before a reversal.\n\n📦 Consolidation\nPrice movement within a tight range.\n\n🚀 Impulse\nA strong one-directional movement.\n\n🔄 Retest\nReturning to a broken level to test it.\n\n🏦 Order Block\nA zone where big players opened large positions.\n\n⏱ Timeframe\nThe time period of a single candle (1m, 5m, 1h).\n\n📊 Breakout\nPrice leaving the support or resistance level.`
        },
        {
            id: 'c1', icon: '⚠️', title: 'Risk Management', desc: 'The process of controlling losses, capital management rules, and protecting your deposit.',
            text: `⚠️ Risk Management\n\nThis is a system of rules that helps a trader control losses and protect capital.\nThe main goal is to not lose the deposit due to a couple of bad trades.\n\n📉 Main Principle\nRisk only a small part of your deposit (1%, 2%, max 5%).\n\n🛡 Basic Rules:\n1️⃣ Limit the risk per trade.\n2️⃣ Do not open too many trades at once.\n3️⃣ Do not try to revenge trade (win back) after a loss.`
        },
        {
            id: 'c2', icon: '📊', title: 'Basic Analysis Foundations', desc: 'Technical and fundamental analysis, levels, trends.',
            text: `📊 Basic Analysis Foundations\n\n(The full course text covers technical analysis, support and resistance levels, trends, indicators, and the basics of fundamental analysis.)\n\n🔹 Technical Analysis\nStudying charts to predict future price movement based on historical data.\n\n🔹 Basic Concepts:\n• Trend — the direction of the price movement (uptrend / downtrend / sideways).\n• Support — buyers' defense level.\n• Resistance — sellers' defense level.\n\n🔹 Types of Analysis:\n1. Technical — analyzing charts and indicators.\n2. Fundamental — analyzing news and economic data (NFP, CPI, GDP).\n3. Sentimental — analyzing market sentiment (fear / greed).`
        },
        {
            id: 'c3', icon: '🎯', title: 'Entry Points (5s OTC)', desc: 'Trading strategy on the 5-second timeframe for OTC using indicators.',
            text: `🎯 Entry Points on 5s OTC\n\n🧠 Why exactly 5 seconds on OTC\nOn OTC charts, an algorithm simulates the market, creating impulses and traps.\n5 seconds show the "breathing" of this algorithm. On this timeframe you:\n• see micro-reversals before they show up on M1;\n• can catch 3-5 second impulses;\n• filter out fake breakouts (by shadows and candle speed).\n\n⚙️ Strategy Setup\nIndicators: Bollinger Bands (14/2.0), EMA 20 + EMA 50, RSI (6, levels 80/20), Parabolic SAR (0.02/0.2).\n\n📊 Bollinger Bands: touching the upper band -> PUT. Touching the lower band -> CALL.\n📈 EMA: EMA 20 crosses EMA 50 upwards -> CALL. Downwards -> PUT.\n⚡ RSI: above 80 -> PUT. Below 20 -> CALL.\n🎯 SAR: dots under the candle -> upward movement. Above the candle -> downward.\n\n🚀 Trading Scenarios\n1. Reversal from a level: price outside BB + RSI > 80 + SAR changed side -> enter against the movement.\n2. Level Breakout: BB expands + EMA crossed -> enter in the direction of the breakout on retest.\n3. Impulse + Pullback: trend + price touches EMA 20 + RSI ≈ 55 -> enter along the trend.\n\n🛡️ Risk Management\n• Do not enter for the first 3-5 minutes of every hour.\n• Max 3 trades in a row in the same direction.\n• 2 losses -> 10 minutes break.`
        },
        {
            id: 'c4', icon: '🕯️', title: 'Patterns', desc: 'Candlestick reversal and trend continuation patterns.',
            text: `🕯️ Patterns in Trading\n\nPatterns are recurring candlestick combinations or chart figures that signal further market movement.\n\n🔹 Reversal Candlestick Patterns:\n• Hammer / Inverted Hammer — long shadow, small body. Reversal signal from support.\n• Engulfing — a large candle completely overlaps the previous one. Strong reversal signal.\n• Doji — open = close, market indecision.\n• Pinbar — a long shadow towards the level, small body. Excellent entry point.\n• Morning / Evening Star — 3 candles, trend change signal.\n\n🔹 Trend Continuation Patterns:\n• Flag — correction against the trend in the form of a parallel channel. Breakout entry.\n• Wedge — narrowing channel. Breakout provides an impulse.\n• Triangle (symmetric, ascending, descending) — accumulation before a breakout.\n\n🔹 How to Apply:\n1. Find a support / resistance level.\n2. Wait for a pattern to form at the level.\n3. Use confirmation: RSI in overbought / oversold zone.\n4. Enter after the pattern candle closes. Stop-loss behind the pattern's shadow.`
        },
        {
            id: 'c5', icon: '📚', title: 'Trading Psychology — Contents', desc: 'Full course program: 8 modules about psychology and the mindset of a trader.',
            text: `📘 Course «Trader Psychology on Forex»\n\n🔹 Introduction\n• Why psychology is more important than strategy.\n• The mistake of 90% of traders — losing money is due to emotions, not lack of market knowledge.\n• The course's goal — to develop psychological endurance.\n\n🔹 Module 1. Foundation of Trading Psychology\nTrader's psyche, emotional biochemistry (adrenaline, cortisol, dopamine), traps (euphoria, fear, excitement, greed), mindfulness and discipline.\n\n🔹 Module 2. Emotions in Trading\nFOMO, fear of losing, greed, excitement, depression. How to distinguish a healthy risk from an emotional one.\n\n🔹 Module 3. Self-Management\nTrading routine, entry/exit rules, trader's journal, stress management, rituals.\n\n🔹 Module 4. Cognitive Biases\nIllusion of control, "I know everything" syndrome, revenge trading, random rewards trap, cognitive distortions.\n\n🔹 Module 5. Money and Psychology\nDeposit and emotions, demo vs real, risk management, lot psychology, attitude towards profits and losses.\n\n🔹 Module 6. Long-term Endurance\nCharacter building, SMART goals, habits, balance, burnout prevention.\n\n🔹 Module 7. Practical Psychology\nSimulations, "emotional stop-loss", visualization, self-assessment, cases.\n\n🔹 Module 8. Professional Psychology\nInstitutional mindset, team work in funds, "cold mind", path from novice to master.\n\n🔹 Conclusion\nCourse summary, "healthy trader" checklist, tips for further development.`
        }
    ],
    LESSONS: [
        {
            id: 1, icon: '🧠', title: 'Module 1. Foundation of trading psychology', desc: 'How the trader\'s psyche works, biochemistry of emotions, and psychological traps.',
            text: `📘 Module 1. Foundation of trading psychology\n\n🔹 1. How the trader's psyche works\nTrading is not just charting, it's a constant stress-test for the psyche.\nA person faces uncertainty, while the brain seeks stability by nature -> hence the mistakes.\n\nBasic reactions:\n• "Fight or flight" — closing trades in panic;\n• "Freeze" — ignoring the loss and hoping for a miracle;\n• "Chase" — opening another trade to win back money.\n\nExample: A trader opened a trade on EUR/USD, it went into minus. Instead of acknowledging the mistake, they "freeze" and move the stop-loss hoping to avoid the loss. The result is a massive loss.\n\n🔹 2. Biochemistry of emotions: adrenaline, cortisol, and dopamine\n• Adrenaline: spikes during unexpected market moves -> prevents rational thinking.\n• Cortisol: stress hormone -> during an extended drawdown, the trader makes mistakes.\n• Dopamine: pleasure hormone -> builds an addiction to "fast winning trades".\n\nExample: 3 profitable trades in a row = high dopamine. The trader thinks "I'm invincible", increases the lot by 5x, and takes a huge loss.\n\n🔹 3. Psychological traps\n• Euphoria — trading "on feeling" without analysis.\n• Fear — blocks decision making, missing good trades.\n• Excitement / Gambling — trading turns into a game.\n• Greed — not fixing the profit in time.\n\n🔹 4. Mindfulness and discipline as the foundation\nDiscipline is the ability to follow the system even when you want to "cheat".\nRules: enter only by signal; risk <=2% of deposit; stop after 3 losses in a row.\n\n✅ The main enemy of a trader is not the market, but their own psyche.`
        },
        {
            id: 2, icon: '😤', title: 'Module 2. Emotions in trading', desc: 'Fear, greed, excitement, and depression — how they affect trades.',
            text: `📘 Module 2. Emotions in trading\n\n🔹 1. Fear\n1.1. Fear Of Missing Out (FOMO)\nFOMO happens when a trader sees movement and thinks: "If I don't enter now — I'll miss my chance".\nExample: EUR/USD rose +100 pips. The trader "jumps" into the market -> price turns around -> loss.\n\n1.2. Fear of loss\nThe trader is afraid to lose money and closes positions too early.\nExample: opened a trade +$50, got scared of a correction, closed -> +$10. 30 mins later the price reached the +$150 target.\n\n🔹 2. Greed and overestimating your skills\nAppears after a winning streak. Drives you to increase risks and hold trades too long.\nExample: a gold trade is +$500. Decided to wait for more -> market flipped -> loss -$200.\n\n🔹 3. Gambling and turning trading into a "casino"\nAfter strong emotions, trading stops being analytical. Example: three minutes -> opens 5 random trades -> blows the account.\n\n🔹 4. Depression after a string of losses\nA few losses shatter your confidence. The trader either abandons the market or trades chaotically.\n\n🔹 5. Healthy risk vs Emotional\n✅ Healthy: systematic trade, stop-loss, risk <=2%, calm decisions.\n❌ Emotional: entering randomly, no stops, increased lot sizes after a loss.\n\n✅ A trader shouldn't fight emotions head-on — they need a system to limit their influence.`
        },
        {
            id: 3, icon: '🎯', title: 'Module 3. Managing yourself', desc: 'Trading routine, trader\'s journal, and stress-coping methods.',
            text: `📘 Module 3. Managing yourself\n\n🔹 1. Creating a trading routine\nChaotic trading = chaotic results. Stability comes from habit.\nExample: "I trade from 10:00 to 13:00. Maximum 3 trades a day." This kills emotional "anytime" entries.\n\n🔹 2. Entry/exit rules and how not to break them\nEntry — only by system signal + 2 confirming factors + risk <=2%.\nExit — fixed stop-loss, take-profit, or carrying over an unprofitable trade "to tomorrow".\nChecklist before entry: ✅ trend, ✅ signal, ✅ risk <=2%.\n\n🔹 3. Keeping a trader's journal\nRecord: date/time, entry reason, plan (stop/take), result, emotions.\nExample entry: EUR/USD buy, bounce off level + RSI -> -20 pips. Emotions: rushing.\nIn a month: 60% of losses are due to "rushing" entries.\n\n🔹 4. Methods to cope with stress\n• 4-7-8 Breathing: inhale for 4s -> hold 7s -> exhale 8s.\n• Physical activity: a walk before/after trading.\n• Micro-breaks: step away from the monitor for 5 mins every 40-60 mins.\n\n🔹 5. How to switch off after trading\nRitual: close terminal -> write in journal -> sports/hobby. This "cuts" the mental connection to trading.\n\n✅ Module 3 teaches you to manage yourself to keep your mind clear and disciplined.`
        },
        {
            id: 4, icon: '🪤', title: 'Module 4. Cognitive biases in trading', desc: 'Cognitive traps: illusion of control, "I know everything" syndrome, revenge trading.',
            text: `📘 Module 4. Cognitive biases in trading\n\n🔹 1. Illusion of control\nThe brain seeks patterns and thinks it can "control the market".\nManifestation: moving the stop-loss, believing "the market has to go my way".\nExample: stop is at -50p -> moves it to -80, -120... Result: loses 7% instead of 1% of the deposit.\n\n🔹 2. "I know everything" syndrome\nAfter a streak of good trades: trading without analysis, ignoring risk management.\nExample: 10 profitable trades -> opens a position 10x larger -> news comes out -> deposit vanishes.\n\n🔹 3. Revenge trading\nThe brain perceives a loss as "injustice". There's an urge to immediately win the money back.\nExample: lost -$200 -> immediately opens a 3x trade -> loss is now -$700.\n\n🔹 4. Random rewards trap\nRandom success reinforces wrong behavior. A trader starts trading randomly.\nExample: accidentally pressed the wrong button and made +$100. Starts trading "on intuition" -> -50% per month.\n\n🔹 5. Cognitive distortions\n• Confirmation bias — only seeking info that confirms your opinion.\n• Sunk cost fallacy — "I've waited 5 mins, there will definitely be a bounce".\n• Recency bias — placing too much weight on the most recent trade result.\n• Herd effect — following chats without personal analysis.\n\n✅ Most mistakes are not technical, but psychological. Solution: system + journal + self-analysis.`
        },
        {
            id: 5, icon: '💰', title: 'Module 5. Money and psychology', desc: 'How deposit size affects emotions, and why demo ≠ real.',
            text: `📘 Module 5. Money and psychology\n\n🔹 1. How deposit sum affects emotions\nSmall account = less fear, more risk. Big account = fear of loss.\nExample: $100 deposit -> easily risks 20%. $10,000 deposit -> even a 1% risk ($100) causes stress.\nConclusion: adjust risk so the sum is psychologically comfortable to lose.\n\n🔹 2. Why "real money" is different from demo\nOn demo, there are no emotions -> calm decisions. On real -> fear, greed, excitement.\nExample: on demo +30% a month. On real with the same entries -> +3% due to fear.\nConclusion: demo is good for systems, but psychology is only trained on real.\n\n🔹 3. Risk-management as a psychological shield\nRule: risk per trade <= 1-2% of deposit.\nExample: $1000 deposit. Risk $100 (10%) -> every minute is stress. Risk $20 (2%) -> a losing streak won't "kill" your psyche.\n\n🔹 4. Lot psychology: 0.01 vs 1.00\nSmall lot -> calm. Big lot -> tension and mistakes.\nExample: EUR/USD lot 0.01 -> holds the trade calmly. Lot 1.00 -> closes the trade at the slightest pullback.\n\n🔹 5. How to be stable with profits and losses\nJudge your performance by how well you follow your plan, not by a single trade's result.\nExample: 3 losses = stress. Focus on the stats over 100 trades = confidence.\n\n✅ Money directly affects emotions. The only way to keep balance is discipline and risk control.`
        },
        {
            id: 6, icon: '🏆', title: 'Module 6. Long-term endurance', desc: 'Character building, realistic goals, and burnout prevention.',
            text: `📘 Module 6. Long-term endurance\n\n🔹 1. Forming a trader's character\nA successful trader is defined by psychological endurance, not a "secret strategy".\nTraits: patience, discipline, ability to wait, resilience to stress. Formed through practice.\nExample: both got a -$100 loss. First one panicked and quit. Second one wrote it in the journal and kept trading the system. Result: the second one is profitable a month later.\n\n🔹 2. Setting realistic goals\nGoals must be SMART: specific, measurable, achievable, realistic.\nUnrealistic: "from $100 to $10,000 in a month".\nRealistic: "stable 3-5% a month for half a year".\n\n🔹 3. Habits of a successful trader\n• Trading exclusively by the system.\n• Keeping a journal.\n• Limiting daily trades.\n• Continuous learning.\n• Emotional control (breathing, sports).\n\n🔹 4. Balance between trading and life\nBalance: work 🔁 rest 🔁 family 🔁 hobbies.\nExample: trading 12 hours a day -> stress, mistakes. Another: 3 hours a day + gym -> fewer trades, but much higher quality.\n\n🔹 5. Burnout point — how not to reach it\nSymptoms: apathy, irritability, loss of interest.\nPrevention: regular breaks, hobbies, strict working hours boundaries.\n\n✅ Trading is a marathon, not a sprint. Only balance and long-term habits lead to stable success.`
        },
        {
            id: 7, icon: '🛠️', title: 'Module 7. Practical psychology', desc: 'Exercises for discipline, "emotional stop-loss", and visualization.',
            text: `📘 Module 7. Practical psychology\n\n🔹 1. Simulations and exercises for discipline\n• Make a trade plan in the morning -> check it in the evening (without actually opening trades).\n• Fixed lot trading: 20 trades in a row with the exact same volume.\n• Pause training: wait 60 seconds before clicking buy/sell to check your emotions.\n\nExample: trade 2 weeks strictly on demo with a journal -> you'll realize you break rules due to emotions, not because of the strategy.\n\n🔹 2. "Emotional stop-loss"\nIf there's anger, gambling, or a desire to "win back money" — trading must be stopped.\n• Limit: max 3-5 trades a day.\n• Rule: 2 losses in a row -> close the terminal.\nExample: after 2 losses went to the gym. The next day entered calmly and recovered the loss.\n\n🔹 3. Visualization and mental techniques\nThe brain doesn't always distinguish real experience from imagined.\nTechniques:\n• Imagine both outcomes (+/-) before entering and accept them calmly.\n• Mentally walk through the steps: entry -> stop -> take -> journal.\n• "Anchor of calmness": a phrase that brings you back to a rational state.\n\nExample: "I accept any outcome, the main thing is to follow the system". This lowers fear.\n\n🔹 4. Self-assessment after every trade\nQuestions: Was the trade systematic? Did I follow risk-management? What emotions did I feel?\nConclusion: even a losing trade can be "correct" if it followed the plan.\n\n🔹 5. Real trader cases\n• Trader A: 5x lot after a profit -> blown account. Mistake: greed. Fix: fixed risk.\n• Trader B: afraid to enter after losses -> missed trades. Mistake: fear. Fix: emotion journal.\n• Trader C: 12 hours a day -> burnout. Mistake: no balance. Fix: time limit.\n\n✅ Module 7 gives practical tools that can be implemented today.`
        },
        {
            id: 8, icon: '👑', title: 'Module 8. Professional psychology', desc: 'Mindset of an institutional trader and the path from novice to master.',
            text: `📘 Module 8. Professional psychology\n\n🔹 1. Mindset of an institutional trader\nInstitutions (banks, funds) trade for a statistical advantage, not "profitable individual trades".\nMain difference: they think in series of trades, not single ones.\nRetail trader: "This trade must be a win".\nInstitutional: "Out of 100 trades, 60 are profitable. This specific one might be a loss — and that's normal".\n\n🔹 2. How teams work in banks and funds\nRoles: analysts -> traders -> risk-managers -> executors.\nEvery step is controlled so that one person's emotions don't lose millions.\nA private trader must build this "control" inside themselves via rules.\n\n🔹 3. Developing a "cold mind"\nA professional stays calm in both profit and loss.\n"Cold mind" = separating emotions from decisions.\nNovice: -$50 loss -> panic. Pro: -$5000 loss -> calmly logs it, because the risk was calculated in advance.\n\n🔹 4. Preparing for major trades\nA pro prepares in advance: analyzes scenarios, accepts both outcomes, lowers the emotional background.\nExample: before NFP, a fund prepares 3 scenarios (run/drop/flat) with a ready plan for each.\n\n🔹 5. The path from novice to master\n• Novice — chaotic trading, belief in the "grail".\n• Student — appearance of a system, trade journal.\n• Experienced — strict risk-management, stable profits.\n• Professional — trading as a business: plan + system + cold mind.\n• Master — teaches others, scales capital.\n\nNovice: "Make $1000 out of $100". Master: "Stable 2-5% a month on $100,000".\n\n✅ The path to success is changing your mindset from amateur to professional. It's not about "guessing the market", it's about building systematic work.`
        }
    ],
    BOOKS: [
        { title: 'Master the Markets', icon: '📘', size: '11.3 MB', file: 'Master the markets.pdf' },
        { title: 'Order Block', icon: '📗', size: '4.6 MB', file: 'Order Block.pdf' },
        { title: 'SMT Divergence', icon: '🧡', size: '5.5 MB', file: 'SMT дивергенция.pdf' },
        { title: 'The Goal', icon: '🎯', size: '2.6 MB', file: 'Smart_reading_Sbornikisammar_Cel_Kak_Opredelyat_I_Dost_mobi.pdf' },
        { title: 'Trading Algorithm', icon: '📕', size: '15.3 MB', file: 'Алексей_Фомин_торговый_алгоритм.pdf' },
        { title: 'Technical Analysis', icon: '📘', size: '6.5 MB', file: 'Джек_Швагер_Технический_анализ_полный_курс.pdf' },
        { title: 'Visual Investor', icon: '📗', size: '16.1 MB', file: 'Джон Мэрфи - Визуальный_инвестор.pdf' },
        { title: 'Imbalance (FVG)', icon: '🧡', size: '4.4 MB', file: 'Имбаланс (Fair Value Gap).pdf' },
        { title: 'Imbalance Types', icon: '🧡', size: '6.0 MB', file: 'Имбаланс — Все Виды.pdf' },
        { title: 'Trading in the Zone', icon: '🎯', size: '1.8 MB', file: 'Марк Дуглас - Зональный Трейдинг.pdf' },
        { title: 'Futures Tech Analysis', icon: '📕', size: '9.3 MB', file: 'Мерфи_Технический_анализ_фьючерсных_рынков.pdf' },
        { title: 'Market Direction', icon: '📈', size: '0.3 MB', file: 'Направление Рынка.pdf' },
        { title: 'Range Trading', icon: '📊', size: '1.3 MB', file: 'РЕНДЖ _ Определение и Торговля.pdf' },
        { title: 'Intelligent Investor', icon: '💡', size: '8.2 MB', file: 'Разумный Инвестор.pdf' },
        { title: 'Fibonacci Trading', icon: '📐', size: '5.7 MB', file: 'Роберт_Фишер_Новые_методы_торговли_по_Фибоначчи.pdf' },
        { title: 'Trading Statistics', icon: '📊', size: '1.4 MB', file: 'Статистика для трейдеров.pdf' },
        { title: 'For Beginners', icon: '📘', size: '7.5 MB', file: 'Технический_анализ_для_начинающих_14.pdf' },
        { title: 'Reminiscences of a Speculator', icon: '📖', size: '1.2 MB', file: 'Эдвин_Лефевр_Воспоминания_биржевого_спекулянта.pdf' },
        { title: 'Trader Encyclopedia', icon: '📚', size: '3.0 MB', file: 'Эрик_Найман_Малая_энциклопедия_трейдера.pdf' }
    ],
    INDICATORS: [
        { icon: '📈', title: 'Bollinger Bands', desc: 'Measure volatility and possible reversals.', text: `<b>Bollinger Bands</b>\nShows market volatility.\n<img src="./bollinger.jpg?v=61" style="width:100%; border-radius:10px; margin:10px 0;">\nTraders use narrowing or widening of the bands to find impulses. The middle line acts as a moving average.` },
        { icon: '📊', title: 'MACD', desc: 'Trend strength oscillator.', text: `<b>MACD</b>\nThe indicator shows the convergence/divergence of moving averages.\n<img src="./macd.jpg?v=61" style="width:100%; border-radius:10px; margin:10px 0;">\nHistogram above zero — bullish trend, below zero — bearish.` },
        { icon: '🔄', title: 'Stochastic Oscillator', desc: 'Finding overbought and oversold zones.', text: `<b>Stochastic</b>\nDetermines price momentum.\n<img src="./stochastic.jpg?v=61" style="width:100%; border-radius:10px; margin:10px 0;">\nValue above 80 = overbought (possible drop). Below 20 = oversold (possible growth).` },
        { icon: '📉', title: 'ADX', desc: 'Trend strength indicator.', text: `<b>ADX</b>\nShows how strong the current trend is.\n<img src="./adx.jpg?v=61" style="width:100%; border-radius:10px; margin:10px 0;">\nAbove 25 — strong trend, under 20 — flat (weak trend).` },
        { icon: '💠', title: 'Fractals', desc: 'Local highs and lows.', text: `<b>Fractals</b>\nHelp find price reversal points.\n<img src="./fractals.jpg?v=61" style="width:100%; border-radius:10px; margin:10px 0;">\nFractal pointing down: support. Fractal pointing up: resistance.` },
        { icon: '🕯️', title: 'RSI', desc: 'Relative Strength Index.', text: `<b>RSI</b>\nEvaluates overbought and oversold states of an asset.\n<img src="./rsi.png?v=61" style="width:100%; border-radius:10px; margin:10px 0;">\nLevels 70 and 30 serve as signal boundaries.` }
    ]
};
module.exports = enContent;
