const frContent = {
    COURSES: [
        {
            id: 'c0', icon: '📊', title: 'Les Bases du Trading', desc: 'Le processus d\'achat et de vente d\'actifs, la liquidité, le déséquilibre et les concepts de base.',
            text: `📊 Qu'est-ce que le Trading\n\nLe trading est le processus d'achat et de vente d'actifs financiers pour gagner sur les variations de prix.\nUn trader analyse le marché, les graphiques et les actualités pour déterminer la direction du prix.\n\n💧 Liquidité\nLa liquidité est la quantité d'argent et d'ordres sur le marché.\nPlus il y a de liquidité, plus il est facile d'acheter ou de vendre un actif.\n\n⚡ Déséquilibre (Imbalance)\nUne zone sur le graphique où le prix s'est déplacé très rapidement et n'a pas laissé de transactions.\nCes zones attirent souvent le prix par la suite.\n\n📉 Support\nUn niveau de prix où les acheteurs commencent activement à acheter l'actif.\n\n📈 Résistance\nUn niveau de prix où les vendeurs commencent activement à vendre.\n\n🕯 Graphique en Chandeliers\nLes bougies montrent le mouvement du prix : ouverture, clôture, plus haut, plus bas.\nUne bougie verte signifie que le prix a augmenté. Rouge signifie qu'il a baissé.\n\n🎯 Tendance\nLa direction générale du prix : tendance haussière, tendance baissière, latérale.\n\n📊 Volatilité\nLa vitesse et la force des changements de prix. Une volatilité plus élevée signifie un marché plus rapide.\n\n🧠 Manipulation du Marché\nMouvement de prix artificiel pour déclencher les ordres stop.\n\n🪤 Prise de Liquidité\nUne cassure spécifique de niveau juste avant un renversement.\n\n📦 Consolidation\nMouvement du prix dans une fourchette étroite.\n\n🚀 Impulsion\nUn mouvement directionnel fort.\n\n🔄 Retest\nRetour à un niveau cassé pour le tester.\n\n🏦 Bloc d'Ordres (Order Block)\nUne zone où les grands acteurs ont ouvert de grandes positions.\n\n⏱ Unité de Temps (Timeframe)\nLa période de temps d'une seule bougie (1m, 5m, 1h).\n\n📊 Cassure (Breakout)\nLe prix quitte la zone de support ou de résistance.`
        },
        {
            id: 'c1', icon: '⚠️', title: 'Gestion des Risques', desc: 'Le processus de contrôle des pertes, les règles de gestion du capital et la protection de votre dépôt.',
            text: `⚠️ Gestion des Risques\n\nC'est un système de règles qui aide un trader à contrôler les pertes et à protéger son capital.\nL'objectif principal est de ne pas perdre de l'argent à cause de quelques mauvaises transactions.\n\n📉 Principe Principal\nNe risquez qu'une petite partie de votre dépôt (1%, 2%, max 5%).\n\n🛡 Règles de Base :\n1️⃣ Limitez le risque par transaction.\n2️⃣ N'ouvrez pas trop de transactions en même temps.\n3️⃣ N'essayez pas de vous venger du marché après une perte.`
        },
        {
            id: 'c2', icon: '📊', title: 'Fondements de Base de l\'Analyse', desc: 'Analyse technique et fondamentale, niveaux, tendances.',
            text: `📊 Fondements de Base de l'Analyse\n\n(Le texte complet du cours couvre l'analyse technique, les niveaux de support et de résistance, les tendances, les indicateurs et les bases de l'analyse fondamentale.)\n\n🔹 Analyse Technique\nÉtude des graphiques pour prédire les mouvements de prix futurs basés sur des données historiques.\n\n🔹 Concepts de Base :\n• Tendance — la direction du mouvement du prix (haussière / baissière / latérale).\n• Support — niveau de défense des acheteurs.\n• Résistance — niveau de défense des vendeurs.\n\n🔹 Types d'Analyse :\n1. Technique — analyse des graphiques et des indicateurs.\n2. Fondamentale — analyse des actualités et des données économiques (NFP, IPC, PIB).\n3. Sentimentale — analyse de l'humeur du marché (peur / cupidité).`
        },
        {
            id: 'c4', icon: '🕯️', title: 'Modèles', desc: 'Modèles de chandeliers de renversement et de continuation de tendance.',
            text: `🕯️ Modèles en Trading\n\nLes modèles sont des combinaisons de bougies qui se répètent ou des figures graphiques qui signalent un mouvement futur du marché.\n\n🔹 Modèles de Chandeliers de Renversement :\n• Marteau / Marteau Inversé — longue ombre, petit corps. Signal de renversement depuis un support.\n• Engloutissement — une grande bougie recouvre complètement la précédente. Fort signal de renversement.\n• Doji — ouverture = clôture, indécision du marché.\n• Pinbar — une longue ombre vers le niveau, petit corps. Excellent point d'entrée.\n• Étoile du Matin / Étoile du Soir — 3 bougies, signal de changement de tendance.\n\n🔹 Modèles de Continuation de Tendance :\n• Drapeau — correction contre la tendance sous forme de canal parallèle. Entrée à la cassure.\n• Biseau — canal qui se rétrécit. La cassure donne une impulsion.\n• Triangle (symétrique, ascendant, descendant) — accumulation avant une cassure.\n\n🔹 Comment les Appliquer :\n1. Trouvez un niveau de support / résistance.\n2. Attendez qu'un modèle se forme à ce niveau.\n3. Utilisez une confirmation : RSI en zone de surachat / survente.\n4. Entrez après la clôture de la bougie du modèle. Stop-loss derrière l'ombre du modèle.`
        },
        {
            id: 'c5', icon: '📚', title: 'Psychologie du Trading — Sommaire', desc: 'Programme complet du cours : 8 modules sur la psychologie et la mentalité du trader.',
            text: `📘 Cours «Psychologie du Trader sur le Forex»\n\n🔹 Introduction\n• Pourquoi la psychologie est plus importante que la stratégie.\n• L'erreur de 90% des traders — perdre de l'argent est dû aux émotions, pas au manque de connaissance du marché.\n• L'objectif du cours — développer l'endurance psychologique.\n\n🔹 Module 1. Fondement de la Psychologie du Trading\nPsyché du trader, biochimie émotionnelle (adrénaline, cortisol, dopamine), pièges (euphorie, peur, excitation, cupidité), pleine conscience et discipline.\n\n🔹 Module 2. Émotions en Trading\nFOMO, peur de perdre, cupidité, excitation, dépression. Comment distinguer un risque sain d'un risque émotionnel.\n\n🔹 Module 3. Gestion de Soi\nRoutine de trading, règles d'entrée/sortie, journal de bord du trader, gestion du stress, rituels.\n\n🔹 Module 4. Biais Cognitifs\nIllusion de contrôle, syndrome "je sais tout", trading de vengeance, piège des récompenses aléatoires, distorsions cognitives.\n\n🔹 Module 5. Argent et Psychologie\nDépôt et émotions, démo vs réel, gestion des risques, psychologie des lots, attitude envers les gains et les pertes.\n\n🔹 Module 6. Endurance à Long Terme\nConstruction du caractère, objectifs SMART, habitudes, équilibre, prévention de l'épuisement professionnel.\n\n🔹 Module 7. Psychologie Pratique\nSimulations, "stop-loss émotionnel", visualisation, auto-évaluation, cas pratiques.\n\n🔹 Module 8. Psychologie Professionnelle\nMentalité institutionnelle, travail d'équipe dans les fonds, "esprit froid", chemin de novice à maître.\n\n🔹 Conclusion\nRésumé du cours, liste de vérification du "trader sain", conseils pour un développement ultérieur.`
        }
    ],
    LESSONS: [
        {
            id: 1, icon: '🧠', title: 'Module 1. Fondement de la psychologie du trading', desc: 'Comment fonctionne la psyché du trader, biochimie des émotions et pièges psychologiques.',
            text: `📘 Module 1. Fondement de la psychologie du trading\n\n🔹 1. Comment fonctionne la psyché du trader\nLe trading n'est pas seulement des graphiques, c'est un test de stress constant pour la psyché.\nUne personne fait face à l'incertitude, alors que le cerveau cherche la stabilité par nature -> d'où les erreurs.\n\nRéactions basiques :\n• "Combat ou fuite" — fermer des transactions en panique ;\n• "Paralysie" — ignorer la perte et espérer un miracle ;\n• "Poursuite" — ouvrir une autre transaction pour récupérer de l'argent.\n\nExemple : Un trader a ouvert une transaction sur EUR/USD, elle passe en négatif. Au lieu de reconnaître l'erreur, il se "paralyse" et déplace le stop-loss en espérant éviter la perte. Le résultat est une perte massive.\n\n🔹 2. Biochimie des émotions : adrénaline, cortisol et dopamine\n• Adrénaline : pics lors de mouvements inattendus du marché -> empêche la pensée rationnelle.\n• Cortisol : hormone du stress -> lors d'un prélèvement prolongé, le trader fait des erreurs.\n• Dopamine : hormone du plaisir -> crée une dépendance aux "transactions gagnantes rapides".\n\nExemple : 3 transactions rentables de suite = dopamine élevée. Le trader pense "Je suis invincible", multiplie le lot par 5, et subit une énorme perte.\n\n🔹 3. Pièges psychologiques\n• Euphorie — trader "au feeling" sans analyse.\n• Peur — bloque la prise de décision, manquant les bonnes transactions.\n• Excitation / Jeu — le trading devient un jeu de hasard.\n• Cupidité — ne pas sécuriser le profit à temps.\n\n🔹 4. Pleine conscience et discipline comme base\nLa discipline est la capacité à suivre le système même lorsque vous voulez "tricher".\nRègles : entrer seulement par signal ; risque <=2% du dépôt ; s'arrêter après 3 pertes de suite.\n\n✅ L'ennemi principal d'un trader n'est pas le marché, mais sa propre psyché.`
        },
        {
            id: 2, icon: '😤', title: 'Module 2. Les émotions en trading', desc: 'Peur, cupidité, excitation et dépression — comment elles affectent les transactions.',
            text: `📘 Module 2. Les émotions en trading\n\n🔹 1. La peur\n1.1. Peur de Manquer (FOMO)\nLe FOMO se produit lorsqu'un trader voit un mouvement et pense : "Si je n'entre pas maintenant — je vais manquer ma chance".\nExemple : EUR/USD a augmenté de +100 pips. Le trader "saute" sur le marché -> le prix se retourne -> perte.\n\n1.2. Peur de perdre\nLe trader a peur de perdre de l'argent et ferme les positions trop tôt.\nExemple : a ouvert une transaction +50$, a eu peur d'une correction, a fermé -> +10$. 30 minutes plus tard, le prix a atteint l'objectif de +150$.\n\n🔹 2. Cupidité et surestimation de ses capacités\nApparaît après une série de gains. Vous pousse à augmenter les risques et à conserver les transactions trop longtemps.\nExemple : une transaction sur l'or est à +500$. Décide d'attendre pour plus -> le marché se retourne -> perte de -200$.\n\n🔹 3. Jeu de hasard et transformer le trading en "casino"\nAprès de fortes émotions, le trading cesse d'être analytique. Exemple : trois minutes -> ouvre 5 transactions au hasard -> détruit son compte.\n\n🔹 4. Dépression après une série de pertes\nQuelques pertes brisent votre confiance. Le trader abandonne le marché ou trade de manière chaotique.\n\n🔹 5. Risque sain vs Émotionnel\n✅ Sain : transaction systématique, stop-loss, risque <=2%, décisions calmes.\n❌ Émotionnel : entrer au hasard, sans stops, tailles de lots augmentées après une perte.\n\n✅ Un trader ne devrait pas combattre les émotions de front — il lui faut un système pour limiter leur influence.`
        },
        {
            id: 3, icon: '🎯', title: 'Module 3. Se gérer soi-même', desc: 'Routine de trading, journal de bord du trader et méthodes pour faire face au stress.',
            text: `📘 Module 3. Se gérer soi-même\n\n🔹 1. Créer une routine de trading\nTrading chaotique = résultats chaotiques. La stabilité vient des habitudes.\nExemple : "Je trade de 10h00 à 13h00. Maximum 3 trades par jour." Cela élimine les entrées émotionnelles "à tout moment".\n\n🔹 2. Règles d'entrée/sortie et comment ne pas les enfreindre\nEntrée — uniquement par signal du système + 2 facteurs de confirmation + risque <=2%.\nSortie — stop-loss fixe, take-profit fixe, ou reporter une position perdante "à demain".\nListe de contrôle avant entrée : ✅ tendance, ✅ signal, ✅ risque <=2%.\n\n🔹 3. Tenir un journal de bord de trader\nEnregistrez : date/heure, raison de l'entrée, plan (stop/take), résultat, émotions.\nExemple d'entrée : Achat EUR/USD, rebond sur niveau + RSI -> -20 pips. Émotions : précipitation.\nEn un mois : 60% des pertes sont dues à des entrées "précipitées".\n\n🔹 4. Méthodes pour gérer le stress\n• Respiration 4-7-8 : inspirez 4s -> retenez 7s -> expirez 8s.\n• Activité physique : une marche avant/après avoir tradé.\n• Micro-pauses : éloignez-vous de l'écran 5 minutes toutes les 40-60 minutes.\n\n🔹 5. Comment décrocher après avoir tradé\nRituel : fermer le terminal -> écrire dans le journal -> sports/hobby. Cela "coupe" la connexion mentale avec le trading.\n\n✅ Le Module 3 vous apprend à vous gérer pour garder l'esprit clair et discipliné.`
        },
        {
            id: 4, icon: '🪤', title: 'Module 4. Biais cognitifs en trading', desc: 'Pièges cognitifs : illusion de contrôle, syndrome du "je sais tout", trading de vengeance.',
            text: `📘 Module 4. Biais cognitifs en trading\n\n🔹 1. Illusion de contrôle\nLe cerveau cherche des motifs et pense qu'il peut "contrôler le marché".\nManifestation : déplacer le stop-loss, croire que "le marché doit aller dans mon sens".\nExemple : le stop est à -50p -> le déplace à -80, -120... Résultat : perd 7% au lieu de 1% du dépôt.\n\n🔹 2. Syndrome "Je sais tout"\nAprès une série de bonnes transactions : trader sans analyse, ignorer la gestion des risques.\nExemple : 10 transactions rentables -> ouvre une position 10x plus grande -> annonce économique -> le dépôt disparaît.\n\n🔹 3. Trading de vengeance (Revenge trading)\nLe cerveau perçoit une perte comme une "injustice". Une envie soudaine de récupérer l'argent se manifeste.\nExemple : perdu -200$ -> ouvre immédiatement une transaction avec un lot 3x -> la perte est maintenant de -700$.\n\n🔹 4. Piège des récompenses aléatoires\nLe hasard conforte un mauvais comportement. Un trader commence à trader de façon aléatoire.\nExemple : a accidentellement cliqué sur le mauvais bouton et gagne +100$. Commence à trader "sur intuition" -> -50% par mois.\n\n🔹 5. Distorsions cognitives\n• Biais de confirmation — chercher uniquement des infos qui confirment votre opinion.\n• Erreur des coûts irrécupérables — "J'ai attendu 5 minutes, il y aura sûrement un rebond".\n• Biais de récence — accorder trop d'importance au résultat du trade le plus récent.\n• Effet grégaire — suivre des salons de discussion sans analyse personnelle.\n\n✅ La plupart des erreurs ne sont pas techniques, mais psychologiques. Solution : système + journal + auto-analyse.`
        },
        {
            id: 5, icon: '💰', title: 'Module 5. L\'argent et la psychologie', desc: 'Comment la taille du dépôt affecte les émotions, et pourquoi la démo ≠ réel.',
            text: `📘 Module 5. L'argent et la psychologie\n\n🔹 1. Comment la somme du dépôt affecte les émotions\nPetit compte = moins de peur, plus de risques. Grand compte = peur de la perte.\nExemple : Dépôt de 100$ -> risque facilement 20%. Dépôt de 10 000$ -> même un risque de 1% (100$) cause du stress.\nConclusion : ajustez le risque afin que la somme soit psychologiquement confortable à perdre.\n\n🔹 2. Pourquoi "l'argent réel" est différent de la démo\nEn démo, il n'y a pas d'émotions -> décisions calmes. En réel -> peur, cupidité, excitation.\nExemple : en démo +30% par mois. En réel avec les mêmes entrées -> +3% dû à la peur.\nConclusion : la démo est bonne pour les systèmes, mais la psychologie ne s'entraîne qu'en réel.\n\n🔹 3. Gestion des risques comme bouclier psychologique\nRègle : le risque par opération ne doit pas dépasser 1-2% du dépôt.\nExemple : Dépôt de 1000$. Risque de 100$ (10%) -> chaque minute est un stress. Risque de 20$ (2%) -> une série de pertes ne "tuera" pas votre psyché.\n\n🔹 4. Psychologie des lots : 0.01 vs 1.00\nPetit lot -> sérénité. Grand lot -> tension et erreurs.\nExemple : lot EUR/USD à 0.01 -> garde le trade sereinement. Lot à 1.00 -> ferme le trade au moindre repli.\n\n🔹 5. Comment être stable avec les gains et les pertes\nJugez vos performances sur le respect de votre plan d'action, pas sur le résultat d'un trade isolé.\nExemple : 3 pertes = stress. Se concentrer sur les statistiques de 100 trades = confiance.\n\n✅ L'argent affecte directement les émotions. La seule façon de garder un équilibre est la discipline et le contrôle du risque.`
        },
        {
            id: 6, icon: '🏆', title: 'Module 6. Endurance à long terme', desc: 'Construction du caractère, objectifs réalistes et prévention de l\'épuisement.',
            text: `📘 Module 6. Endurance à long terme\n\n🔹 1. Forger un caractère de trader\nUn trader a succès se définit par son endurance psychologique, pas par une "stratégie secrète".\nTraits : patience, discipline, capacité d'attente, résilience au stress. Se forge par la pratique.\nExemple : deux traders font une perte de -100$. Le premier panique et arrête. Le second l'écrit dans son journal et continue d'appliquer le système. Résultat : le second est rentable un mois plus tard.\n\n🔹 2. Fixer des objectifs réalistes\nLes objectifs doivent être SMART : spécifiques, mesurables, atteignables, réalistes.\nIrréaliste : "de 100$ à 10 000$ en un mois".\nRéaliste : "3-5% stables par mois pendant six mois".\n\n🔹 3. Habitudes d'un trader qui a réussi\n• Trade exclusivement selon son système.\n• Tient un journal de bord méticuleusement.\n• Limite les trades quotidiens.\n• Apprentissage continu.\n• Contrôle des émotions (respiration, sport).\n\n🔹 4. Équilibre entre le trading et la vie\nÉquilibre : travail 🔁 repos 🔁 famille 🔁 loisirs.\nExemple : trader 12 heures par jour -> stress, erreurs. Un autre profil : 3 heures par jour + salle de sport -> moins de trades, mais d'une qualité bien supérieure.\n\n🔹 5. Syndrome de l'Épuisement (Burnout) — comment l'éviter\nSymptômes : apathie, irritabilité, perte d'intérêt.\nPrévention : pauses régulières, passe-temps, limites d'heures de travail strictes.\n\n✅ Le trading est un marathon, pas un sprint. Seuls l'équilibre et des habitudes sur le long terme mènent au succès durable.`
        },
        {
            id: 7, icon: '🛠️', title: 'Module 7. Psychologie pratique', desc: 'Exercices pour la discipline, "stop-loss émotionnel" et visualisation.',
            text: `📘 Module 7. Psychologie pratique\n\n🔹 1. Simulations et exercices pour la discipline\n• Préparez un plan de trading le matin -> vérifiez-le le soir (sans ouvrir réellement de trades).\n• Trading à lot fixe : 20 trades consécutifs avec exactement le même volume.\n• Entraînement à la pause : attendez 60 secondes avant de cliquer sur acheter/vendre pour canaliser vos émotions.\n\nExemple : tradez 2 semaines de façon stricte en démo avec un journal de bord -> vous réaliserez que vos erreurs viennent de l'émotionnel, pas de la stratégie.\n\n🔹 2. "Stop-loss émotionnel"\nS'il y a de la colère, des pulsions de jeu, ou la volonté de "se refaire" — le trading doit cesser.\n• Limite : max 3-5 trades par jour.\n• Règle : 2 pertes consécutives -> on ferme le terminal.\nExemple : après 2 pertes, le trader est allé au sport. Le lendemain, il entre calmement, suit son système, et efface sa perte.\n\n🔹 3. Visualisation et techniques mentales\nLe cerveau ne fait pas toujours la distinction entre une expérience vécue et imaginée.\nTechniques :\n• Imaginez chaque issue du trade (+/-) avant d'entrer et acceptez-les sereinement.\n• Parcourez mentalement toutes les étapes : entrée -> stop-loss -> take-profit -> tenir le journal.\n• « Ancre de calme » : phrase rassurante qui vous ramène à un état réfléchi.\n\nExemple : "J'accepte toute issue de marché, le plus important est de suivre ma méthode."\n\n🔹 4. Auto-évaluation systématique après chaque trade\nQuestions : Le trade fait-il partie du système ? La gestion du risque a-t-elle été suivie ? Quelles ont été mes émotions ?\nConclusion : même un trade perdant peut être "bon" s'il respecte le système.\n\n🔹 5. Études de cas réels\n• Trader A : lot multiplié par 5 après gain -> détruit son compte. Mauvaise gestion : cupidité. Solution stricte : risque systématique fixe.\n• Trader B : a peur d'entrer après des pertes -> rate son entrée. Mauvaise gestion : Peur. Solution : Journal d'émotions.\n• Trader C : 12h de trading/jour -> Burnout. Mauvaise gestion : absence d’équilibre. Solution : Limite de temps horaire.\n\n✅ Le Module 7 propose des actions pratiques immédiatement applicables.`
        },
        {
            id: 8, icon: '👑', title: 'Module 8. Psychologie des professionnels', desc: 'Mentalité d\'un trader institutionnel et parcours du débutant au maître.',
            text: `📘 Module 8. Psychologie des professionnels\n\n🔹 1. Mentalité institutionnelle\nLes institutions (banques, fonds) tradent pour un avantage statistique fondé, et ne recherchent pas le "miracle du trade individuel".\nDifférence clé : ils évaluent l'avantage mathématique en groupes de trades (par ex. 100), pas sur la prochaine transaction.\nTrader de détail : "Cette position doit être la bonne."\nInstitutionnalisé : "Sur 100 transactions, 60 sont gagnantes. Celle-ci aboutira au hasard des probabilités en perte, et c'est parfaitement normal."\n\n🔹 2. Fonctionnement des fonds d'investissement\nRôles définis : analystes -> traders -> gestionnaires de risques -> exécutants.\nChaque phase fait l'objet d'instructions fermes pour prévenir qu'une décision d'humeur individuelle engendre des pertes massives.\nUn trader indépendant doit instaurer le même niveau d'encadrement en lui, par l'imposition de cadres normés.\n\n🔹 3. Développer un « Esprit de Glace »\nL'expert observe sans exprimer d'émotion, peu importent la finalité du trade (positif / négatif).\n« Esprit formel » = la déconnexion complète du sentiment et de la décision.\nNovice : perds 50$ -> panique totale. Pro : perte de 5000$ -> est consigné et enregistré à froid, sachant que la perte était planifiée à l'avance.\n\n🔹 4. Anticipation des grands événements économiques\nUn professionnel détermine des plans à l'avance : scénarios décryptés des deux options, et modère la composante émotionnelle.\nExemple pour le NFP : définit les contextes 3, puis agit sereinement peu importe l'indication de l'actif.\n\n🔹 5. Le processus de Novice à Maître\n• Novice : mode de pari aléatoire (trading casino) qui est très exposé à la dépendance émotionnelle.\n• Apprenti : commencement du système, tenue assidue des journaux.\n• Habitué : maîtrise de l'analyse, la protection du risque est établie.\n• Professionnel : le mode est entrepreneurial complet.\n• Maître : transmet l'expérience à autrui et scale une approche monomatique de haut investissement sans perte de conscience.\n\n✅ Le chemin du succès dépend entièrement de votre transition psychologie / structure.`
        }
    ],
    BOOKS: [
        { title: 'Master the Markets', icon: '📘', size: '11.3 MB', file: 'Master the markets.pdf' },
        { title: 'Order Block', icon: '📗', size: '4.6 MB', file: 'Order Block.pdf' },
        { title: 'Divergence SMT', icon: '🧡', size: '5.5 MB', file: 'SMT дивергенция.pdf' },
        { title: 'Le But', icon: '🎯', size: '2.6 MB', file: 'Smart_reading_Sbornikisammar_Cel_Kak_Opredelyat_I_Dost_mobi.pdf' },
        { title: 'Algorithme de Trading', icon: '📕', size: '15.3 MB', file: 'Алексей_Фомин_торговый_алгоритм.pdf' },
        { title: 'Analyse Technique', icon: '📘', size: '6.5 MB', file: 'Джек_Швагер_Технический_анализ_полный_курс.pdf' },
        { title: 'Investisseur Visuel', icon: '📗', size: '16.1 MB', file: 'Джон Мэрфи - Визуальный_инвестор.pdf' },
        { title: 'Imbalance (FVG)', icon: '🧡', size: '4.4 MB', file: 'Имбаланс (Fair Value Gap).pdf' },
        { title: 'Types d\'Imbalance', icon: '🧡', size: '6.0 MB', file: 'Имбаланс — Все Виды.pdf' },
        { title: 'Trading in the Zone', icon: '🎯', size: '1.8 MB', file: 'Марк Дуглас - Зональный Трейдинг.pdf' },
        { title: 'L\'Analyse des Marchés', icon: '📕', size: '9.3 MB', file: 'Мерфи_Технический_анализ_фьючерсных_рынков.pdf' },
        { title: 'Direction du Marché', icon: '📈', size: '0.3 MB', file: 'Направление Рынка.pdf' },
        { title: 'Trading de Range', icon: '📊', size: '1.3 MB', file: 'РЕНДЖ _ Определение и Торговля.pdf' },
        { title: 'Investisseur Intelligent', icon: '💡', size: '8.2 MB', file: 'Разумный Инвестор.pdf' },
        { title: 'Trading de Fibonacci', icon: '📐', size: '5.7 MB', file: 'Роберт_Фишер_Новые_методы_торговли_по_Фибоначчи.pdf' },
        { title: 'Stats de Trading', icon: '📊', size: '1.4 MB', file: 'Статистика для трейдеров.pdf' },
        { title: 'Pour les Débutants', icon: '📘', size: '7.5 MB', file: 'Технический_анализ_для_начинающих_14.pdf' },
        { title: 'Mémoires d\'un Spéculateur', icon: '📖', size: '1.2 MB', file: 'Эдвин_Лефевр_Воспоминания_биржевого_спекулянта.pdf' },
        { title: 'Encyclopédie du Trader', icon: '📚', size: '3.0 MB', file: 'Эрик_Найман_Малая_энциклопедия_трейдера.pdf' }
    ],
    INDICATORS: [
        { icon: '📈', title: 'Bandes de Bollinger', desc: 'Mesure la volatilité et les renversements possibles.', text: `<b>Bandes de Bollinger</b>\nIndique la volatilité du marché.\n<img src="./bollinger.jpg?v=61" style="width:100%; border-radius:10px; margin:10px 0;">\nLes traders utilisent le rétrécissement ou l'élargissement des bandes pour trouver des impulsions. La ligne centrale agit comme une moyenne mobile.` },
        { icon: '📊', title: 'MACD', desc: 'Oscillateur de force de tendance.', text: `<b>MACD</b>\nL'indicateur montre la convergence/divergence des moyennes mobiles.\n<img src="./macd.jpg?v=61" style="width:100%; border-radius:10px; margin:10px 0;">\nHistogramme au-dessus de zéro — tendance haussière, en dessous de zéro — baissière.` },
        { icon: '🔄', title: 'Oscillateur Stochastique', desc: 'Recherche de zones de surachat et de survente.', text: `<b>Stochastique</b>\nDétermine l'élan du prix.\n<img src="./stochastic.jpg?v=61" style="width:100%; border-radius:10px; margin:10px 0;">\nUne valeur supérieure à 80 = surachat (baisse possible). Inférieure à 20 = survente (hausse possible).` },
        { icon: '📉', title: 'ADX', desc: 'Indicateur de force de tendance.', text: `<b>ADX</b>\nMontre l'intensité de la tendance actuelle.\n<img src="./adx.jpg?v=61" style="width:100%; border-radius:10px; margin:10px 0;">\nAu-dessus de 25 — forte tendance, en dessous de 20 — marché plat (tendance faible).` },
        { icon: '💠', title: 'Fractales', desc: 'Plus hauts et plus bas locaux.', text: `<b>Fractales</b>\nAident à trouver des points de retournement des prix.\n<img src="./fractals.jpg?v=61" style="width:100%; border-radius:10px; margin:10px 0;">\nFractale pointant vers le bas : support. Fractale pointant vers le haut : résistance.` },
        { icon: '🕯️', title: 'RSI', desc: 'Relative Strength Index.', text: `<b>RSI</b>\nÉvalue les états de surachat et de survente d'un actif.\n<img src="./rsi.png?v=61" style="width:100%; border-radius:10px; margin:10px 0;">\nLes niveaux de 70 et de 30 servent de limites pour les signaux.` }
    ]
};
module.exports = frContent;
