const esContent = {
    COURSES: [
        {
            id: 'c0', icon: '📊', title: 'Conceptos Básicos de Trading', desc: 'El proceso de compra y venta de activos, liquidez, desequilibrios y conceptos básicos.',
            text: `📊 Qué es el Trading\n\nEl trading es el proceso de compra y venta de activos financieros para ganar con los cambios de precio.\nUn trader analiza el mercado, los gráficos y las noticias para determinar hacia dónde puede ir el precio.\n\n💧 Liquidez\nLa liquidez es la cantidad de dinero y órdenes en el mercado.\nCuanta más liquidez haya, más fácil será comprar o vender un activo.\n\n⚡ Desequilibrio (Imbalance)\nUna zona en el gráfico donde el precio se movió muy rápido y no dejó operaciones.\nEstas zonas a menudo atraen el precio de vuelta más adelante.\n\n📉 Soporte\nUn nivel de precio donde los compradores comienzan a comprar activamente el activo.\n\n📈 Resistencia\nUn nivel de precio donde los vendedores comienzan a vender activamente.\n\n🕯 Gráfico de Velas\nLas velas muestran el movimiento del precio: apertura, cierre, máximo, mínimo.\nUna vela verde significa que el precio subió. Roja significa que bajó.\n\n🎯 Tendencia\nLa dirección general del precio: tendencia alcista, bajista, lateral.\n\n📊 Volatilidad\nLa velocidad y fuerza de los cambios de precio. Mayor volatilidad significa un mercado más rápido.\n\n🧠 Manipulación del Mercado\nMovimiento artificial del precio para atrapar órdenes de stop.\n\n🪤 Toma de Liquidez\nUna ruptura específica de nivel justo antes de una reversión.\n\n📦 Consolidación\nMovimiento del precio dentro de un rango estrecho.\n\n🚀 Impulso\nUn fuerte movimiento unidireccional.\n\n🔄 Retesteo\nRegreso a un nivel roto para probarlo.\n\n🏦 Bloque de Órdenes (Order Block)\nUna zona donde los grandes jugadores abrieron grandes posiciones.\n\n⏱ Temporalidad (Timeframe)\nEl período de tiempo de una sola vela (1m, 5m, 1h).\n\n📊 Ruptura (Breakout)\nEl precio abandona el nivel de soporte o resistencia.`
        },
        {
            id: 'c1', icon: '⚠️', title: 'Gestión de Riesgos', desc: 'El proceso de controlar pérdidas, reglas de gestión de capital y proteger el depósito.',
            text: `⚠️ Gestión de Riesgos\n\nEste es un sistema de reglas que ayuda a un trader a controlar las pérdidas y proteger su capital.\nEl objetivo principal es no perder el depósito por un par de malas operaciones.\n\n📉 Principio Principal\nArriesga solo una pequeña parte de tu depósito (1%, 2%, máximo 5%).\n\n🛡 Reglas Básicas:\n1️⃣ Limita el riesgo por operación.\n2️⃣ No abras demasiadas operaciones a la vez.\n3️⃣ No intentes vengarte del mercado (recuperar) después de una pérdida.`
        },
        {
            id: 'c2', icon: '📊', title: 'Fundamentos Básicos de Análisis', desc: 'Análisis técnico y fundamental, niveles, tendencias.',
            text: `📊 Fundamentos Básicos de Análisis\n\n(El texto completo del curso cubre análisis técnico, niveles de soporte y resistencia, tendencias, indicadores y conceptos básicos del análisis fundamental.)\n\n🔹 Análisis Técnico\nEstudio de los gráficos para predecir movimientos de precios futuros basados en datos históricos.\n\n🔹 Conceptos Básicos:\n• Tendencia — la dirección del movimiento del precio (alcista / bajista / lateral).\n• Soporte — nivel de defensa de los compradores.\n• Resistencia — nivel de defensa de los vendedores.\n\n🔹 Tipos de Análisis:\n1. Técnico — análisis de gráficos e indicadores.\n2. Fundamental — análisis de noticias y datos económicos (NFP, IPC, PIB).\n3. Sentimental — análisis del estado de ánimo del mercado (miedo / codicia).`
        },
        {
            id: 'c3', icon: '🎯', title: 'Puntos de Entrada (5s OTC)', desc: 'Estrategia de trading en temporalidad de 5 segundos para OTC usando indicadores.',
            text: `🎯 Puntos de Entrada en 5s OTC\n\n🧠 ¿Por qué exactamente 5 segundos en OTC?\nEn los gráficos OTC, un algoritmo simula el mercado, creando impulsos y trampas.\n5 segundos muestran la "respiración" de este algoritmo. En esta temporalidad tú:\n• ves micro-reversiones antes de que aparezcan en M1;\n• puedes capturar impulsos de 3-5 segundos;\n• filtras falsas rupturas (por sombras y velocidad de las velas).\n\n⚙️ Configuración de la Estrategia\nIndicadores: Bandas de Bollinger (14/2.0), EMA 20 + EMA 50, RSI (6, niveles 80/20), Parabolic SAR (0.02/0.2).\n\n📊 Bandas de Bollinger: toca la banda superior -> PUT. Toca la banda inferior -> CALL.\n📈 EMA: EMA 20 cruza EMA 50 hacia arriba -> CALL. Hacia abajo -> PUT.\n⚡ RSI: arriba de 80 -> PUT. Debajo de 20 -> CALL.\n🎯 SAR: puntos debajo de la vela -> movimiento alcista. Arriba de la vela -> bajista.\n\n🚀 Escenarios de Trading\n1. Reversión desde un nivel: precio fuera de BB + RSI > 80 + SAR cambió de lado -> entra contra el movimiento.\n2. Ruptura de nivel: BB se expande + EMA se cruzan -> entra en dirección a la ruptura en el retesteo.\n3. Impulso + Retroceso: tendencia + precio toca EMA 20 + RSI ≈ 55 -> entra a favor de la tendencia.\n\n🛡️ Gestión de Riesgos\n• No operes los primeros 3-5 minutos de cada hora.\n• Máximo 3 operaciones seguidas en la misma dirección.\n• 2 pérdidas -> 10 minutos de descanso.`
        },
        {
            id: 'c4', icon: '🕯️', title: 'Patrones', desc: 'Patrones de velas de reversión y continuación de tendencia.',
            text: `🕯️ Patrones de Trading\n\nLos patrones son combinaciones recurrentes de velas o figuras de gráficos que señalan un movimiento futuro del mercado.\n\n🔹 Patrones de Velas de Reversión:\n• Martillo / Martillo Invertido — sombra larga, cuerpo pequeño. Señal de reversión desde soporte.\n• Envolvente — una vela grande envuelve completamente a la anterior. Señal de reversión fuerte.\n• Doji — apertura = cierre, indecisión del mercado.\n• Pinbar — una sombra larga hacia el nivel, cuerpo pequeño. Excelente punto de entrada.\n• Estrella de la Mañana / Estrella de la Tarde — 3 velas, señal de cambio de tendencia.\n\n🔹 Patrones de Continuación de Tendencia:\n• Bandera — corrección contra la tendencia en forma de canal paralelo. Entrada en la ruptura.\n• Cuña — canal que se estrecha. La ruptura proporciona un impulso.\n• Triángulo (simétrico, ascendente, descendente) — acumulación antes de una ruptura.\n\n🔹 Cómo Aplicarlo:\n1. Encuentra un nivel de soporte / resistencia.\n2. Espera a que se forme un patrón en el nivel.\n3. Usa confirmación: RSI en zona de sobrecompra / sobreventa.\n4. Entra después de que cierre la vela del patrón. Stop-loss detrás de la sombra del patrón.`
        },
        {
            id: 'c5', icon: '📚', title: 'Psicología del Trading — Contenido', desc: 'Programa completo del curso: 8 módulos sobre psicología y mentalidad del trader.',
            text: `📘 Curso «Psicología del Trader en Forex»\n\n🔹 Introducción\n• Por qué la psicología es más importante que la estrategia.\n• El error del 90% de los traders — perder dinero se debe a las emociones, no a la falta de conocimiento del mercado.\n• El objetivo del curso — desarrollar resistencia psicológica.\n\n🔹 Módulo 1. Fundamento de la Psicología del Trading\nPsique del trader, bioquímica emocional (adrenalina, cortisol, dopamina), trampas (euforia, miedo, excitación, codicia), atención plena y disciplina.\n\n🔹 Módulo 2. Emociones en el Trading\nFOMO, miedo a perder, codicia, excitación, depresión. Cómo distinguir un riesgo saludable de uno emocional.\n\n🔹 Módulo 3. Gestión de sí mismo\nRutina de trading, reglas de entrada/salida, diario del trader, manejo del estrés, rituales.\n\n🔹 Módulo 4. Sesgos Cognitivos\nIlusión de control, síndrome de "lo sé todo", trading de venganza, trampa de recompensas aleatorias, distorsiones cognitivas.\n\n🔹 Módulo 5. Dinero y Psicología\nDepósito y emociones, demo vs real, gestión de riesgos, psicología del lote, actitud hacia ganancias y pérdidas.\n\n🔹 Módulo 6. Resistencia a Largo Plazo\nConstrucción del carácter, metas SMART, hábitos, equilibrio, prevención del agotamiento.\n\n🔹 Módulo 7. Psicología Práctica\nSimulaciones, "stop-loss emocional", visualización, autoevaluación, casos.\n\n🔹 Módulo 8. Psicología Profesional\nMentalidad institucional, trabajo en equipo en fondos, "mente fría", camino de novato a maestro.\n\n🔹 Conclusión\nResumen del curso, lista de verificación del "trader saludable", consejos para mayor desarrollo.`
        }
    ],
    LESSONS: [
        {
            id: 1, icon: '🧠', title: 'Módulo 1. Fundamentos de psicología', desc: 'Cómo funciona la mente del trader, bioquímica de las emociones y trampas psicológicas.',
            text: `📘 Módulo 1. Fundamentos de psicología de trading\n\n🔹 1. Cómo funciona la mente del trader\nEl trading no es solo gráficos, es una prueba de estrés constante para la psique.\nUna persona enfrenta incertidumbre, mientras que el cerebro busca estabilidad por naturaleza -> de ahí los errores.\n\nReacciones básicas:\n• "Lucha o huida" — cerrar operaciones por pánico;\n• "Paralizarse" — ignorar la pérdida y esperar un milagro;\n• "Perseguir" — abrir otra operación para recuperar dinero.\n\nEjemplo: Un trader abrió una operación en EUR/USD, y fue a pérdida. En lugar de reconocer el error, se "paraliza" y mueve el stop-loss esperando evitar la pérdida. El resultado es una pérdida masiva.\n\n🔹 2. Bioquímica de las emociones: adrenalina, cortisol y dopamina\n• Adrenalina: picos durante movimientos inesperados del mercado -> impide el pensamiento racional.\n• Cortisol: hormona del estrés -> durante una caída prolongada, el trader comete errores.\n• Dopamina: hormona del placer -> crea una adicción a las "operaciones ganadoras rápidas".\n\nEjemplo: 3 operaciones rentables seguidas = mucha dopamina. El trader piensa "Soy invencible", aumenta el lote 5 veces y sufre una pérdida enorme.\n\n🔹 3. Trampas psicológicas\n• Euforia — operar "por intuición" sin análisis.\n• Miedo — bloquea la toma de decisiones, perdiéndose buenas operaciones.\n• Excitación / Apuestas — el trading se convierte en un juego.\n• Codicia — no asegurar la ganancia a tiempo.\n\n🔹 4. Consciencia y disciplina como bases\nLa disciplina es la capacidad de seguir el sistema incluso cuando quieres "hacer trampa".\nReglas: entra solo por señal; riesgo <=2% del depósito; detenerse tras 3 pérdidas seguidas.\n\n✅ El principal enemigo de un trader no es el mercado, sino su propia mente.`
        },
        {
            id: 2, icon: '😤', title: 'Módulo 2. Emociones en el trading', desc: 'Miedo, codicia, excitación y depresión — cómo afectan las operaciones.',
            text: `📘 Módulo 2. Emociones en el trading\n\n🔹 1. Miedo\n1.1. Miedo a Perderse Algo (FOMO)\nEl FOMO ocurre cuando un trader ve movimiento y piensa: "Si no entro ahora, perderé mi oportunidad".\nEjemplo: EUR/USD subió +100 pips. El trader "salta" al mercado -> el precio se da la vuelta -> pérdida.\n\n1.2. Miedo a perder\nEl trader teme perder dinero y cierra posiciones demasiado pronto.\nEjemplo: abrió una operación +$50, se asustó por una corrección, cerró -> +$10. 30 minutos después el precio alcanzó la meta de +$150.\n\n🔹 2. Codicia y sobreestimación de tus habilidades\nAparece después de una racha ganadora. Te impulsa a aumentar riesgos y mantener operaciones demasiado tiempo.\nEjemplo: una operación de oro está +$500. Decidido a esperar más -> el mercado giró -> pérdida -$200.\n\n🔹 3. Apuestas y convertir el trading en un "casino"\nDespués de emociones fuertes, el trading deja de ser analítico. Ejemplo: tres minutos -> abre 5 operaciones al azar -> quema la cuenta.\n\n🔹 4. Depresión después de una racha de pérdidas\nUnas cuantas pérdidas destruyen tu confianza. El trader abandona el mercado o opera caóticamente.\n\n🔹 5. Riesgo Saludable vs Emocional\n✅ Saludable: operación sistemática, stop-loss, riesgo <=2%, decisiones tranquilas.\n❌ Emocional: entrar al azar, sin stops, tamaños de lote aumentados tras una pérdida.\n\n✅ Un trader no debería luchar contra las emociones frontalmente — necesita un sistema para limitar su influencia.`
        },
        {
            id: 3, icon: '🎯', title: 'Módulo 3. Gestión de ti mismo', desc: 'Rutina de trading, diario del trader y métodos para afrontar el estrés.',
            text: `📘 Módulo 3. Gestión de ti mismo\n\n🔹 1. Creando una rutina de trading\nTrading caótico = resultados caóticos. La estabilidad proviene del hábito.\nEjemplo: "Opero de 10:00 a 13:00. Máximo 3 operaciones al día". Esto mata las entradas emocionales "en cualquier momento".\n\n🔹 2. Reglas de entrada/salida y cómo no romperlas\nEntrada — solo por señal del sistema + 2 factores de confirmación + riesgo <=2%.\nSalida — stop-loss fijo, take-profit fijo, o mantener una operación perdedora "hasta mañana".\nLista de verificación previa a la entrada: ✅ tendencia, ✅ señal, ✅ riesgo <=2%.\n\n🔹 3. Mantener un diario de trader\nRegistra: fecha/hora, motivo de entrada, plan (stop/take), resultado, emociones.\nEjemplo de entrada: EUR/USD compra, rebote en nivel + RSI -> -20 pips. Emociones: prisa.\nEn un mes: el 60% de las pérdidas se deben a entradas "con prisa".\n\n🔹 4. Métodos para lidiar con el estrés\n• Respiración 4-7-8: inhala 4s -> retén 7s -> exhala 8s.\n• Actividad física: un paseo antes/después de operar.\n• Micro-descansos: aléjate del monitor 5 minutos cada 40-60 minutos.\n\n🔹 5. Cómo desconectar después de operar\nRitual: cierra el terminal -> escribe en el diario -> deportes/hobby. Esto "corta" la conexión mental con el trading.\n\n✅ El Módulo 3 te enseña a gestionarte a ti mismo para mantener tu mente clara y disciplinada.`
        },
        {
            id: 4, icon: '🪤', title: 'Módulo 4. Sesgos cognitivos', desc: 'Trampas cognitivas: ilusión de control, síndrome de "lo sé todo", trading de venganza.',
            text: `📘 Módulo 4. Sesgos cognitivos en el trading\n\n🔹 1. Ilusión de control\nEl cerebro busca patrones y piensa que puede "controlar el mercado".\nManifestación: mover el stop-loss, creer "el mercado tiene que ir a mi favor".\nEjemplo: el stop está en -50p -> lo mueve a -80, -120... Resultado: pierde el 7% en lugar del 1% del depósito.\n\n🔹 2. Síndrome de "lo sé todo"\nTras una racha de buenas operaciones: operar sin análisis, ignorar la gestión de riesgos.\nEjemplo: 10 operaciones rentables -> abre una posición 10x mayor -> salen noticias -> el depósito se esfuma.\n\n🔹 3. Trading de venganza\nEl cerebro percibe una pérdida como "injusticia". Surge el impulso de recuperar el dinero inmediatamente.\nEjemplo: perdió -$200 -> abre inmediatamente una operación 3x -> la pérdida es ahora de -$700.\n\n🔹 4. Trampa de recompensas aleatorias\nEl éxito aleatorio refuerza el comportamiento equivocado. El trader empieza a operar al azar.\nEjemplo: pulsó accidentalmente el botón equivocado y ganó +$100. Empieza a operar "por intuición" -> -50% al mes.\n\n🔹 5. Distorsiones cognitivas\n• Sesgo de confirmación — buscar solo información que confirme tu opinión.\n• Falacia de los costos hundidos — "He esperado 5 minutos, seguro que habrá un rebote".\n• Sesgo de inmediatez — dar demasiado peso al resultado de la operación más reciente.\n• Efecto rebaño — seguir chats sin análisis personal.\n\n✅ La mayoría de los errores no son técnicos, sino psicológicos. Solución: sistema + diario + autoanálisis.`
        },
        {
            id: 5, icon: '💰', title: 'Módulo 5. Dinero y psicología', desc: 'Cómo el tamaño del depósito afecta las emociones y por qué demo ≠ real.',
            text: `📘 Módulo 5. Dinero y psicología\n\n🔹 1. Cómo la suma del depósito afecta las emociones\nCuenta pequeña = menos miedo, más riesgo. Cuenta grande = miedo a perder.\nEjemplo: Depósito de $100 -> arriesga fácilmente el 20%. Depósito de $10,000 -> incluso un riesgo del 1% ($100) causa estrés.\nConclusión: ajusta el riesgo para que la suma sea psicológicamente cómoda de perder.\n\n🔹 2. Por qué el "dinero real" es diferente de la demo\nEn la demo, no hay emociones -> decisiones calmadas. En real -> miedo, codicia, excitación.\nEjemplo: en demo +30% al mes. En real con las mismas entradas -> +3% debido al miedo.\nConclusión: la demo es buena para los sistemas, pero la psicología solo se entrena en real.\n\n🔹 3. Gestión de riesgos como escudo psicológico\nRegla: riesgo por operación <= 1-2% del depósito.\nEjemplo: Depósito de $1000. Riesgo de $100 (10%) -> cada minuto es estrés. Riesgo de $20 (2%) -> una racha perdedora no "matará" tu psique.\n\n🔹 4. Psicología del lote: 0.01 vs 1.00\nLote pequeño -> calma. Lote grande -> tensión y errores.\nEjemplo: EUR/USD lote 0.01 -> mantiene la operación con calma. Lote 1.00 -> cierra la operación al menor retroceso.\n\n🔹 5. Cómo ser estable con ganancias y pérdidas\nJuzga tu desempeño por lo bien que sigues tu plan, no por el resultado de una sola operación.\nEjemplo: 3 pérdidas = estrés. Enfócate en las estadísticas sobre 100 operaciones = confianza.\n\n✅ El dinero afecta directamente las emociones. La única manera de mantener el equilibrio es la disciplina y el control de riesgos.`
        },
        {
            id: 6, icon: '🏆', title: 'Módulo 6. Resistencia a largo plazo', desc: 'Construcción del carácter, metas realistas y prevención del agotamiento.',
            text: `📘 Módulo 6. Resistencia a largo plazo\n\n🔹 1. Formando el carácter de un trader\nUn trader exitoso se define por la resistencia psicológica, no por una "estrategia secreta".\nRasgos: paciencia, disciplina, capacidad de esperar, resiliencia al estrés. Formado mediante la práctica.\nEjemplo: ambos tuvieron una pérdida de -$100. El primero entró en pánico y renunció. El segundo lo anotó en el diario y continuó operando su sistema. Resultado: el segundo es rentable un mes después.\n\n🔹 2. Establecer metas realistas\nLas metas deben ser SMART: específicas, medibles, alcanzables, realistas.\nIrreal: "de $100 a $10,000 en un mes".\nRealista: "3-5% estable al mes durante medio año".\n\n🔹 3. Hábitos de un trader exitoso\n• Operar exclusivamente por el sistema.\n• Mantener un diario.\n• Limitar las operaciones diarias.\n• Aprendizaje continuo.\n• Control emocional (respiración, deportes).\n\n🔹 4. Equilibrio entre el trading y la vida\nEquilibrio: trabajo 🔁 descanso 🔁 familia 🔁 hobbies.\nEjemplo: operando 12 horas al día -> estrés, errores. Otro: 3 horas al día + gimnasio -> menos operaciones, pero mucha mayor calidad.\n\n🔹 5. Punto de agotamiento — cómo no alcanzarlo\nSíntomas: apatía, irritabilidad, pérdida de interés.\nPrevención: descansos regulares, hobbies, límites estrictos del horario de trabajo.\n\n✅ El trading es una maratón, no un sprint. Solo el equilibrio y los hábitos a largo plazo conducen al éxito estable.`
        },
        {
            id: 7, icon: '🛠️', title: 'Módulo 7. Psicología práctica', desc: 'Ejercicios de disciplina, "stop-loss emocional" y visualización.',
            text: `📘 Módulo 7. Psicología práctica\n\n🔹 1. Simulaciones y ejercicios para la disciplina\n• Haz un plan de trading por la mañana -> revísalo por la noche (sin abrir operaciones realmente).\n• Operación de lote fijo: 20 operaciones seguidas exactamente con el mismo volumen.\n• Entrenamiento de pausa: espera 60 segundos antes de hacer clic en comprar/vender para verificar tus emociones.\n\nEjemplo: opera 2 semanas estrictamente en demo con un diario -> te darás cuenta de que rompes las reglas debido a las emociones, no por la estrategia.\n\n🔹 2. "Stop-loss emocional"\nSi hay enojo, apuestas o deseo de "recuperar el dinero" — el trading debe detenerse.\n• Límite: máximo 3-5 operaciones al día.\n• Regla: 2 pérdidas seguidas -> cerrar el terminal.\nEjemplo: después de 2 pérdidas fue al gimnasio. Al día siguiente entró tranquilo y recuperó la pérdida.\n\n🔹 3. Visualización y técnicas mentales\nEl cerebro no siempre distingue la experiencia real de la imaginada.\nTécnicas:\n• Imagina ambos resultados (+/-) antes de entrar y acéptalos tranquilamente.\n• Repasa mentalmente los pasos: entrada -> stop -> take -> diario.\n• "Ancla de calma": una frase que te devuelve a un estado racional.\n\nEjemplo: "Acepto cualquier resultado, lo principal es seguir el sistema". Esto reduce el miedo.\n\n🔹 4. Autoevaluación después de cada operación\nPreguntas: ¿Fue la operación sistemática? ¿Seguí la gestión de riesgos? ¿Qué emociones sentí?\nConclusión: incluso una operación con pérdidas puede ser "correcta" si siguió el plan.\n\n🔹 5. Casos de traders reales\n• Trader A: lote 5x después de una ganancia -> cuenta quemada. Error: codicia. Solución: riesgo fijo.\n• Trader B: miedo a entrar tras pérdidas -> pierde operaciones. Error: miedo. Solución: diario de emociones.\n• Trader C: 12 horas al día -> agotamiento. Error: sin equilibrio. Solución: límite de tiempo.\n\n✅ El Módulo 7 ofrece herramientas prácticas que pueden implementarse hoy mismo.`
        },
        {
            id: 8, icon: '👑', title: 'Módulo 8. Psicología profesional', desc: 'Mentalidad de un trader institucional y el camino de novato a experto.',
            text: `📘 Módulo 8. Psicología profesional\n\n🔹 1. Mentalidad de un trader institucional\nLas instituciones (bancos, fondos) operan por una ventaja estadística, no por "operaciones individuales rentables".\nDiferencia principal: piensan en series de operaciones, no en unas solas.\nTrader minorista: "Esta operación debe ser ganadora".\nInstitucional: "De 100 operaciones, 60 son rentables. Esta en específico podría ser una pérdida — y eso es normal".\n\n🔹 2. Cómo trabajan los equipos en bancos y fondos\nRoles: analistas -> traders -> gestores de riesgos -> ejecutores.\nCada paso se controla para que las emociones de una sola persona no pierdan millones.\nUn trader privado debe construir este "control" dentro de sí mismo mediante reglas.\n\n🔹 3. Desarrollando una "mente fría"\nUn profesional se mantiene tranquilo tanto en la ganancia como en la pérdida.\n"Mente fría" = separar emociones de decisiones.\nNovato: pérdida de -$50 -> pánico. Pro: pérdida de -$5000 -> lo registra tranquilamente, porque el riesgo fue calculado de antemano.\n\n🔹 4. Preparándose para grandes operaciones\nUn profesional se prepara de antemano: analiza escenarios, acepta ambos resultados, reduce el trasfondo emocional.\nEjemplo: antes de NFP, un fondo prepara 3 escenarios (alza/baja/rango) con un plan listo para cada uno.\n\n🔹 5. El camino de novato a maestro\n• Novato — trading caótico, creencia en el "grial".\n• Estudiante — aparición de un sistema, diario de trading.\n• Avezado — gestión de riesgos estricta, ganancias estables.\n• Profesional — el trading como negocio: plan + sistema + mente fría.\n• Maestro — enseña a otros, escala capital.\n\nNovato: "Hacer $1000 de $100". Maestro: "2-5% estable al mes sobre $100,000".\n\n✅ El camino hacia el éxito es cambiar tu mentalidad de aficionado a profesional. No se trata de "adivinar el mercado", sino de construir un trabajo sistemático.`
        }
    ],
    BOOKS: [
        { title: 'Master the Markets', icon: '📘', size: '11.3 MB', file: 'Master the markets.pdf' },
        { title: 'Order Block', icon: '📗', size: '4.6 MB', file: 'Order Block.pdf' },
        { title: 'Divergencia SMT', icon: '🧡', size: '5.5 MB', file: 'SMT дивергенция.pdf' },
        { title: 'La Meta', icon: '🎯', size: '2.6 MB', file: 'Smart_reading_Sbornikisammar_Cel_Kak_Opredelyat_I_Dost_mobi.pdf' },
        { title: 'Algoritmo de Trading', icon: '📕', size: '15.3 MB', file: 'Алексей_Фомин_торговый_алгоритм.pdf' },
        { title: 'Análisis Técnico', icon: '📘', size: '6.5 MB', file: 'Джек_Швагер_Технический_анализ_полный_курс.pdf' },
        { title: 'Inversor Visual', icon: '📗', size: '16.1 MB', file: 'Джон Мэрфи - Визуальный_инвестор.pdf' },
        { title: 'Desequilibrio (FVG)', icon: '🧡', size: '4.4 MB', file: 'Имбаланс (Fair Value Gap).pdf' },
        { title: 'Tipos de Desequilibrio', icon: '🧡', size: '6.0 MB', file: 'Имбаланс — Все Виды.pdf' },
        { title: 'Trading en la Zona', icon: '🎯', size: '1.8 MB', file: 'Марк Дуглас - Зональный Трейдинг.pdf' },
        { title: 'Análisis Técnico Futuros', icon: '📕', size: '9.3 MB', file: 'Мерфи_Технический_анализ_фьючерсных_рынков.pdf' },
        { title: 'Dirección del Mercado', icon: '📈', size: '0.3 MB', file: 'Направление Рынка.pdf' },
        { title: 'Trading en Rangos', icon: '📊', size: '1.3 MB', file: 'РЕНДЖ _ Определение и Торговля.pdf' },
        { title: 'El Inversor Inteligente', icon: '💡', size: '8.2 MB', file: 'Разумный Инвестор.pdf' },
        { title: 'Trading con Fibonacci', icon: '📐', size: '5.7 MB', file: 'Роберт_Фишер_Новые_методы_торговли_по_Фибоначчи.pdf' },
        { title: 'Estadísticas de Trading', icon: '📊', size: '1.4 MB', file: 'Статистика для трейдеров.pdf' },
        { title: 'Para Principiantes', icon: '📘', size: '7.5 MB', file: 'Технический_анализ_для_начинающих_14.pdf' },
        { title: 'Recuerdos de un Operador', icon: '📖', size: '1.2 MB', file: 'Эдвин_Лефевр_Воспоминания_биржевого_спекулянта.pdf' },
        { title: 'Enciclopedia de Trader', icon: '📚', size: '3.0 MB', file: 'Эрик_Найман_Малая_энциклопедия_трейдера.pdf' }
    ],
    INDICATORS: [
        { icon: '📈', title: 'Bandas de Bollinger', desc: 'Mide la volatilidad y posibles reversiones.', text: `<b>Bandas de Bollinger</b>\nMuestra la volatilidad del mercado.\n<img src="./bollinger.jpg?v=61" style="width:100%; border-radius:10px; margin:10px 0;">\nLos traders usan el estrechamiento o la expansión de las bandas para encontrar impulsos. La línea media actúa como media móvil.` },
        { icon: '📊', title: 'MACD', desc: 'Oscilador de fuerza de tendencia.', text: `<b>MACD</b>\nEl indicador muestra la convergencia/divergencia de las medias móviles.\n<img src="./macd.jpg?v=61" style="width:100%; border-radius:10px; margin:10px 0;">\nEl histograma sobre cero corresponde a una tendencia alcista, debajo de cero — bajista.` },
        { icon: '🔄', title: 'Oscilador Estocástico', desc: 'Buscando zonas de sobrecompra y sobreventa.', text: `<b>Estocástico</b>\nDetermina el momento del precio.\n<img src="./stochastic.jpg?v=61" style="width:100%; border-radius:10px; margin:10px 0;">\nUn valor superior a 80 = sobrecompra (posible caída). Inferior a 20 = sobreventa (posible crecimiento).` },
        { icon: '📉', title: 'ADX', desc: 'Indicador de fuerza de tendencia.', text: `<b>ADX</b>\nMuestra cuán fuerte es la tendencia actual.\n<img src="./adx.jpg?v=61" style="width:100%; border-radius:10px; margin:10px 0;">\nPor encima de 25 — tendencia fuerte, debajo de 20 — lateral (tendencia débil).` },
        { icon: '💠', title: 'Fractales', desc: 'Máximos y mínimos locales.', text: `<b>Fractales</b>\nAyudan a localizar puntos de reversión de precios.\n<img src="./fractals.jpg?v=61" style="width:100%; border-radius:10px; margin:10px 0;">\nFractal apuntando hacia abajo: soporte. Fractal apuntando hacia arriba: resistencia.` },
        { icon: '🕯️', title: 'RSI', desc: 'Índice de Fuerza Relativa.', text: `<b>RSI</b>\nEvalúa los estados de sobrecompra y sobreventa de un activo.\n<img src="./rsi.png?v=61" style="width:100%; border-radius:10px; margin:10px 0;">\nLos niveles 70 y 30 sirven como zonas de señales de límites.` }
    ]
};
module.exports = esContent;
